{% set name = "gwemopt" %}
{% set version = "0.4.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gwemopt-{{ version }}.tar.gz
  sha256: 2979215d0307bfc51c950128d15abfce0a8983c1a2af0adb219f43452059fde6

build:
  entry_points:
    - gwemopt-run=gwemopt.run:run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }},<3.14
    - numba
    - numpy >=2.0
    - scipy >=1.14
    - matplotlib-base >=3.5
    - astropy-base >=6.0
    - astropy-healpix
    - mocpy >=0.16.0
    - astroquery
    - astroplan
    - ephem
    - joblib
    - igwn-segments
    - ligo.skymap
    - lxml
    - h5py
    - healpy
    - pandas
    - shapely
    - pytables
    - requests
    - tqdm
    - regions

test:
  imports:
    - gwemopt
  commands:
    - pip check
    - gwemopt-run --help
  requires:
    - pip

about:
  home: https://github.com/skyportal/gwemopt
  summary: A python package for GW-EM Followup Optimization
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Theodlz
    - mcoughlin
