{% set name = "gwemopt" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gwemopt-{{ version }}.tar.gz
  sha256: 2e1bd4c7354eee819ad1eacfcbd0be59568489e7aa7989b17086fd890d6b208e

build:
  entry_points:
    - gwemopt-run=gwemopt.run:run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - setuptools-scm
    - pip
  run:
    - python >=3.8
    - numpy >=1.7.1
    - scipy >=1.2.1
    - matplotlib-base >=1.2.0
    - astropy >=1.1.1
    - astropy-healpix
    - python-dateutil
    - mocpy >=0.12.2
    - astroquery
    - astroplan
    - ephem
    - pyyaml
    - pulp
    - voeventlib
    - joblib
    - ligo-segments
    - ligo.skymap
    - lxml
    - h5py
    - healpy
    - ortools-python
    - pandas
    - shapely
    - pytables
    - regions
    - tqdm

test:
  imports:
    - gwemopt
  commands:
    - pip check
    - gwemopt-run --help
  requires:
    - pip

about:
  home: https://github.com/skyportal/gwemopt
  summary: A python package for GW-EM Followup Optimization
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mcoughlin
